server:
  port: 9191

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: usuario
          uri: lb://usuario
          predicates:
            - Path=/users/**
        - id: departamentos
          uri: lb://departamentos
          predicates:
            - Path=/departments/**
          filters:
            - RewritePath=/departments/(?<segment>.*), /departments/${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost